# Generated by Django 6.0.2 on 2026-02-24 19:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Question text')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False')], default='multiple_choice', help_text='Type of question', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within quiz')),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the correct answer', null=True)),
                ('points', models.PositiveIntegerField(default=1, help_text='Points for correct answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'question',
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('educator', 'Educator'), ('citizen', 'Citizen')], default='citizen', help_text='User role in the platform', max_length=20)),
                ('bio', models.TextField(blank=True, help_text='User biography', null=True)),
                ('profile_image', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='profiles/')),
                ('is_email_verified', models.BooleanField(default=False, help_text='Email verification status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'custom_user',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Comment content')),
                ('is_edited', models.BooleanField(default=False, help_text='Whether comment has been edited')),
                ('likes_count', models.PositiveIntegerField(default=0, help_text='Number of likes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Comment author', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent comment (for nested replies)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.comment')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(help_text='Comment being liked', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.comment')),
                ('user', models.ForeignKey(help_text='User who liked', on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment Like',
                'verbose_name_plural': 'Comment Likes',
                'db_table': 'comment_like',
            },
        ),
        migrations.CreateModel(
            name='DiscussionThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Thread title', max_length=255)),
                ('content', models.TextField(help_text='Thread content')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pinned', 'Pinned')], default='open', help_text='Thread status', max_length=20)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin thread to top')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Number of views')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Thread creator', on_delete=django.db.models.deletion.CASCADE, related_name='discussion_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discussion Thread',
                'verbose_name_plural': 'Discussion Threads',
                'db_table': 'discussion_thread',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(help_text='Parent thread', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.discussionthread'),
        ),
        migrations.CreateModel(
            name='LearningModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Module title', max_length=255, unique=True)),
                ('description', models.TextField(help_text='Module description')),
                ('content', models.TextField(help_text='Module main content')),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Publication status', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('image', models.ImageField(blank=True, help_text='Module cover image', null=True, upload_to='modules/')),
                ('attachment', models.FileField(blank=True, help_text='Additional PDF or document', null=True, upload_to='modules/attachments/')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', help_text='Difficulty level', max_length=20)),
                ('estimated_time', models.PositiveIntegerField(default=15, help_text='Estimated reading time in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(help_text='Educator who created this module', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_modules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Module',
                'verbose_name_plural': 'Learning Modules',
                'db_table': 'learning_module',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Related module (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_threads', to='core.learningmodule'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Choice text')),
                ('is_correct', models.BooleanField(default=False, help_text='Mark if this is correct answer')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(help_text='Parent question', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.question')),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
                'db_table': 'choice',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Quiz title', max_length=255)),
                ('description', models.TextField(help_text='Quiz description')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Quiz difficulty', max_length=20)),
                ('total_questions', models.PositiveIntegerField(default=0, help_text='Total number of questions (auto-calculated)')),
                ('passing_score', models.PositiveIntegerField(default=60, help_text='Minimum score to pass (%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_limit', models.PositiveIntegerField(blank=True, help_text='Time limit in minutes', null=True)),
                ('is_published', models.BooleanField(default=False, help_text='Quiz visibility')),
                ('shuffle_questions', models.BooleanField(default=True, help_text='Randomize question order')),
                ('show_answers', models.BooleanField(default=True, help_text='Show correct answers after completion')),
                ('max_attempts', models.PositiveIntegerField(blank=True, help_text='Maximum attempts (null = unlimited)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Educator who created quiz', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quizzes', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(help_text='Associated learning module', on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='core.learningmodule')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'db_table': 'quiz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(help_text='Parent quiz', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.quiz'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(blank=True, help_text='Total score obtained', null=True)),
                ('total_possible_score', models.PositiveIntegerField(default=0, help_text='Total possible score')),
                ('percentage', models.FloatField(blank=True, help_text='Score percentage', null=True)),
                ('is_passed', models.BooleanField(blank=True, help_text='Whether user passed the quiz', null=True)),
                ('total_questions_attempted', models.PositiveIntegerField(default=0, help_text='Questions answered')),
                ('total_questions_correct', models.PositiveIntegerField(default=0, help_text='Correct answers')),
                ('time_taken', models.PositiveIntegerField(blank=True, help_text='Time taken in seconds', null=True)),
                ('quiz', models.ForeignKey(help_text='Quiz attempted', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.quiz')),
                ('user', models.ForeignKey(help_text='User who took the quiz', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
                'db_table': 'quiz_attempt',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, help_text='Whether answer was correct')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(help_text='Question answered', on_delete=django.db.models.deletion.CASCADE, to='core.question')),
                ('selected_choice', models.ForeignKey(blank=True, help_text='Choice selected by user', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.choice')),
                ('attempt', models.ForeignKey(help_text='Quiz attempt this answer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.quizattempt')),
            ],
            options={
                'verbose_name': 'Question Answer',
                'verbose_name_plural': 'Question Answers',
                'db_table': 'question_answer',
                'ordering': ['attempt', 'question__order'],
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='custom_user_role_aeef4e_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='custom_user_email_55dec9_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['comment', 'user'], name='comment_lik_comment_321837_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('comment', 'user')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['thread', 'author'], name='comment_thread__990a75_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent'], name='comment_parent__834718_idx'),
        ),
        migrations.AddIndex(
            model_name='learningmodule',
            index=models.Index(fields=['status', 'order'], name='learning_mo_status_f7b50f_idx'),
        ),
        migrations.AddIndex(
            model_name='learningmodule',
            index=models.Index(fields=['slug'], name='learning_mo_slug_6caaf0_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionthread',
            index=models.Index(fields=['-is_pinned', '-created_at'], name='discussion__is_pinn_5c2acc_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionthread',
            index=models.Index(fields=['module', 'status'], name='discussion__module__f0782f_idx'),
        ),
        migrations.AddIndex(
            model_name='choice',
            index=models.Index(fields=['question', 'is_correct'], name='choice_questio_3ebf03_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['module', 'is_published'], name='quiz_module__a6f47d_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['quiz', 'order'], name='question_quiz_id_f5028d_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'quiz'], name='quiz_attemp_user_id_bee8ab_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['is_passed'], name='quiz_attemp_is_pass_ec0bee_idx'),
        ),
    ]
